env:
    es6: true
    node: true
extends: 'eslint:recommended'
parserOptions:
    sourceType: module
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
    camelcase:
        - error
        - properties: always
    dot-notation:
        - error
        - allowKeywords: true
    comma-dangle:
        - error
        - always-multiline
